packages:
- mellon/
- mellon-server/
- mellon-client/
- mellon-pi/
resolver: nightly-2015-10-19
extra-deps:
- servant-lucid-0.4.4.5
- HPi-0.5.1

# Use these for the local libbcm2835 install path.
extra-include-dirs:
- /usr/local/include
extra-lib-dirs:
- /usr/local/lib
