packages:
- mellon/
- mellon-server/
- mellon-client/
- mellon-gpio/
- location:
    git: git@github.com:dhess/gpio.git
    commit: eaa10c3e3d744bf8b44adef3dec18d11b068db16
resolver: lts-3.17
extra-deps:
- servant-lucid-0.4.4.5
