packages:
- mellon/
- mellon-server/
- mellon-client/
- mellon-gpio/
- location:
    git: git@github.com:dhess/gpio.git
    commit: 2eb1233bafc8ea10fb0ac6028f09dd2266346b29
resolver: lts-3.17
extra-deps:
- servant-lucid-0.4.4.5
