packages:
- mellon/
- mellon-server/
- mellon-client/
- mellon-gpio/
- location:
    git: git@github.com:dhess/gpio.git
    commit: d82498813c2c5ba50243140d34006015f10c2722
resolver: lts-5.1
extra-deps:
- servant-lucid-0.4.4.5
